### ISSUE TITLE
laravel9中无法获取Content-Type: application/json提供的内容

### ISSUE THREAD

**Issue by heirychen** [joanhey/AdapterMan#29]
```
public function store(TestRequest $request){
    return $request->all();
}
```

报以下错误

```
TypeError: Symfony\Component\HttpFoundation\Request::createRequestFromFactory(): Argument #2 ($request) must be of type array, null given, called in /home/user/php/test/vendor/symfony/http-foundation/Request.php on line 295 and defined in /home/user/php/test/vendor/symfony/http-foundation/Request.php:1913
Stack trace:
#0 /home/user/php/test/vendor/symfony/http-foundation/Request.php(295): Symfony\Component\HttpFoundation\Request::createRequestFromFactory()
#1 /home/user/php/test/vendor/laravel/framework/src/Illuminate/Http/Request.php(68): Symfony\Component\HttpFoundation\Request::createFromGlobals()
#2 /home/user/php/test/start.php(62): Illuminate\Http\Request::capture()
#3 /home/user/php/test/server.php(21): run()
#4 /home/user/php/test/vendor/workerman/workerman/Connection/TcpConnection.php(656): {closure}()
#5 /home/user/php/test/vendor/workerman/workerman/Events/Select.php(292): Workerman\Connection\TcpConnection->baseRead()
#6 /home/user/php/test/vendor/workerman/workerman/Worker.php(2410): Workerman\Events\Select->loop()
#7 /home/user/php/test/vendor/workerman/workerman/Worker.php(1543): Workerman\Worker->run()
#8 /home/user/php/test/vendor/workerman/workerman/Worker.php(1373): Workerman\Worker::forkOneWorkerForLinux()
#9 /home/user/php/test/vendor/workerman/workerman/Worker.php(1347): Workerman\Worker::forkWorkersForLinux()
#10 /home/user/php/test/vendor/workerman/workerman/Worker.php(547): Workerman\Worker::forkWorkers()
#11 /home/user/php/test/server.php(24): Workerman\Worker::runAll()
#12 {main}
Worker[14315] process terminated
worker[AdapterMan:14315] exit with status 64000
^CWorkerman[server.php] stopping ...
Workerman[server.php] has been stopped
```

**Comment by joanhey** [comment]
I don't understand Chinese, please write in English.

Are you using Adapterman v0.5.x or the master branch?

**Comment by joanhey** [comment]
Fixed in master https://github.com/joanhey/AdapterMan/commit/595f9a8ae950c77ff5b780bddaa77cc7762eb620
