### ISSUE TITLE
After using swoole, using ctrl + C to close the service will report an error

### ISSUE THREAD

**Issue by wcydeyouxiang** [joanhey/AdapterMan#30]
```shell
Fatal error: Uncaught Swoole\ExitException: swoole exit in /www/vendor/workerman/workerman/Worker.php:1861
Stack trace:
#0 /www/vendor/workerman/workerman/Worker.php(1172): Workerman\Worker::stopAll()
#1 [internal function]: Workerman\Worker::signalHandler(2, Array)
#2 /www/vendor/workerman/workerman/Events/Swoole.php(52): pcntl_signal_dispatch()
#3 [internal function]: Workerman\Events\Swoole->Workerman\Events\{closure}(1)
#4 {main}
  thrown in /www/vendor/workerman/workerman/Worker.php on line 1861

Fatal error: Uncaught Swoole\ExitException: swoole exit in /www/vendor/workerman/workerman/Worker.php:1861
Stack trace:
#0 /www/vendor/workerman/workerman/Worker.php(1172): Workerman\Worker::stopAll()
#1 [internal function]: Workerman\Worker::signalHandler(2, Array)
#2 /www/vendor/workerman/workerman/Events/Swoole.php(52): pcntl_signal_dispatch()
#3 [internal function]: Workerman\Events\Swoole->Workerman\Events\{closure}(1)
#4 {main}
  thrown in /www/vendor/workerman/workerman/Worker.php on line 1861

Fatal error: Uncaught Swoole\ExitException: swoole exit in /www/vendor/workerman/workerman/Worker.php:1861
Stack trace:
#0 /www/vendor/workerman/workerman/Worker.php(1172): Workerman\Worker::stopAll()
#1 [internal function]: Workerman\Worker::signalHandler(2, Array)
#2 /www/vendor/workerman/workerman/Events/Swoole.php(52): pcntl_signal_dispatch()
#3 [internal function]: Workerman\Events\Swoole->Workerman\Events\{closure}(1)
#4 {main}
  thrown in /www/vendor/workerman/workerman/Worker.php on line 1861

Fatal error: Uncaught Swoole\ExitException: swoole exit in /www/vendor/workerman/workerman/Worker.php:1861
Stack trace:
#0 /www/vendor/workerman/workerman/Worker.php(1172): Workerman\Worker::stopAll()
#1 [internal function]: Workerman\Worker::signalHandler(2, Array)
#2 /www/vendor/workerman/workerman/Events/Swoole.php(52): pcntl_signal_dispatch()
#3 [internal function]: Workerman\Events\Swoole->Workerman\Events\{closure}(1)
#4 {main}
  thrown in /www/vendor/workerman/workerman/Worker.php on line 1861

Fatal error: Uncaught Swoole\ExitException: swoole exit in /www/vendor/workerman/workerman/Worker.php:1861
Stack trace:
#0 /www/vendor/workerman/workerman/Worker.php(1172): Workerman\Worker::stopAll()
#1 [internal function]: Workerman\Worker::signalHandler(2, Array)
#2 /www/vendor/workerman/workerman/Events/Swoole.php(52): pcntl_signal_dispatch()
#3 [internal function]: Workerman\Events\Swoole->Workerman\Events\{closure}(1)
#4 {main}
  thrown in /www/vendor/workerman/workerman/Worker.php on line 1861

Fatal error: Uncaught Swoole\ExitException: swoole exit in /www/vendor/workerman/workerman/Worker.php:1861
Stack trace:
#0 /www/vendor/workerman/workerman/Worker.php(1172): Workerman\Worker::stopAll()
#1 [internal function]: Workerman\Worker::signalHandler(2, Array)
#2 /www/vendor/workerman/workerman/Events/Swoole.php(52): pcntl_signal_dispatch()
#3 [internal function]: Workerman\Events\Swoole->Workerman\Events\{closure}(1)
#4 {main}
  thrown in /www/vendor/workerman/workerman/Worker.php on line 1861

Fatal error: Uncaught Swoole\ExitException: swoole exit in /www/vendor/workerman/workerman/Worker.php:1861
Stack trace:
#0 /www/vendor/workerman/workerman/Worker.php(1172): Workerman\Worker::stopAll()
#1 [internal function]: Workerman\Worker::signalHandler(2, Array)
#2 /www/vendor/workerman/workerman/Events/Swoole.php(52): pcntl_signal_dispatch()
#3 [internal function]: Workerman\Events\Swoole->Workerman\Events\{closure}(1)
#4 {main}
  thrown in /www/vendor/workerman/workerman/Worker.php on line 1861
worker[AdapterMan:474] exit with status 65280
worker[AdapterMan:471] exit with status 65280
worker[AdapterMan:470] exit with status 65280
worker[AdapterMan:472] exit with status 65280
worker[AdapterMan:473] exit with status 65280
worker[AdapterMan:475] exit with status 65280
worker[AdapterMan:477] exit with status 65280

   Symfony\Component\ErrorHandler\Error\FatalError 

  Uncaught Swoole\ExitException: swoole exit in /www/vendor/workerman/workerman/Worker.php:1861
Stack trace:
#0 /www/vendor/workerman/workerman/Worker.php(1172): Workerman\Worker::stopAll()
#1 [internal function]: Workerman\Worker::signalHandler(2, Array)
#2 /www/vendor/workerman/workerman/Events/Swoole.php(52): pcntl_signal_dispatch()
#3 [internal function]: Workerman\Events\Swoole->Workerman\Events\{closure}(1)
#4 {main}
  thrown

  at vendor/workerman/workerman/Worker.php:1861
    1857▕                 static::$_workers = array();
    1858▕                 if (static::$globalEvent) {
    1859▕                     static::$globalEvent->destroy();
    1860▕                 }
  ➜ 1861▕                 exit(0);
    1862▕             }
    1863▕         }
    1864▕     }
    1865▕ 


   Whoops\Exception\ErrorException 

  Uncaught Swoole\ExitException: swoole exit in /www/vendor/workerman/workerman/Worker.php:1861
Stack trace:
#0 /www/vendor/workerman/workerman/Worker.php(1172): Workerman\Worker::stopAll()
#1 [internal function]: Workerman\Worker::signalHandler(2, Array)
#2 /www/vendor/workerman/workerman/Events/Swoole.php(52): pcntl_signal_dispatch()
#3 [internal function]: Workerman\Events\Swoole->Workerman\Events\{closure}(1)
#4 {main}
  thrown

  at vendor/workerman/workerman/Worker.php:1861
    1857▕                 static::$_workers = array();
    1858▕                 if (static::$globalEvent) {
    1859▕                     static::$globalEvent->destroy();
    1860▕                 }
  ➜ 1861▕                 exit(0);
    1862▕             }
    1863▕         }
    1864▕     }
    1865▕ 

      +1 vendor frames 
  2   [internal]:0
      Whoops\Run::handleShutdown()
worker[AdapterMan:476] exit with status 65280
Workerman[server.php] has been stopped
```

**Comment by wcydeyouxiang** [comment]
There is no such problem after using the dev-master version
