### ISSUE TITLE
使用php 8.2和thinkphp8.0报错

### ISSUE THREAD

**Issue by xujinhui2015** [joanhey/AdapterMan#49]
我使用php 8.2和thinkphp8.0，命令行输入能正常启动，但是网页一访问这个链接就报错误，不知道是什么问题

PS D:\project_php\outdoors> php -c cli-php.ini server.php start
Adapterman v0.6.1 OK
---------------------------------------------- WORKERMAN -----------------------------------------------
Workerman version:4.1.13          PHP version:8.2.3
----------------------------------------------- WORKERS ------------------------------------------------
worker                                          listen                              processes   status
AdapterMan                                      http://127.0.0.1:12345              1           [ok]
Error: Call to undefined function run() in D:\project_php\outdoors\server.php:21
Stack trace:
#0 D:\project_php\outdoors\vendor\workerman\workerman\Connection\TcpConnection.php(646): {closure}(Object(Workerman\Connection\TcpConnection), Array)
#1 D:\project_php\outdoors\vendor\workerman\workerman\Events\Select.php(311): Workerman\Connection\TcpConnection->baseRead(Resource id #47)
#2 D:\project_php\outdoors\vendor\workerman\workerman\Worker.php(1485): Workerman\Events\Select->loop()
#3 D:\project_php\outdoors\vendor\workerman\workerman\Worker.php(1402): Workerman\Worker::forkWorkersForWindows()
#4 D:\project_php\outdoors\vendor\workerman\workerman\Worker.php(560): Workerman\Worker::forkWorkers()
#5 D:\project_php\outdoors\server.php(24): Workerman\Worker::runAll()
#6 {main}

**Comment by joanhey** [comment]
It's really clear the error

```
Error: Call to undefined function run() in D:\project_php\outdoors\server.php:21
Stack trace:
```

Do you load the think.php file in the Server.php ?
https://github.com/joanhey/AdapterMan/blob/master/src/frameworks/think.php
