### ISSUE TITLE
Call to undefined function `run()`

### ISSUE THREAD

**Issue by foremtehan** [joanhey/AdapterMan#64]
I installed a fresh laravel app and just required the package and did what everything said in https://github.com/joanhey/AdapterMan/blob/master/recipes/laravel.md

But when i run the server and browse the route / i get the following error:

```
Error: Call to undefined function run() in /app/server.php:21
Stack trace:
#0 /app/vendor/workerman/workerman/Connection/TcpConnection.php(646): {closure}(Object(Workerman\Connection\TcpConnection), Array)
#1 /app/vendor/workerman/workerman/Events/Select.php(311): Workerman\Connection\TcpConnection->baseRead(Resource id #89)
#2 /app/vendor/workerman/workerman/Worker.php(1635): Workerman\Events\Select->loop()
#3 /app/vendor/workerman/workerman/Worker.php(1426): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#4 /app/vendor/workerman/workerman/Worker.php(1400): Workerman\Worker::forkWorkersForLinux()
#5 /app/vendor/workerman/workerman/Worker.php(1785): Workerman\Worker::forkWorkers()
#6 /app/vendor/workerman/workerman/Worker.php(1721): Workerman\Worker::monitorWorkersForLinux()
#7 /app/vendor/workerman/workerman/Worker.php(562): Workerman\Worker::monitorWorkers()
#8 /app/server.php(24): Workerman\Worker::runAll()
```

Steps to reproduce:

https://github.com/joanhey/AdapterMan/assets/53290883/bfe219e1-5aa1-4b70-86a9-984859a0e009

**Comment by joanhey** [comment]
Where is the `<?php` in the `start.php` ??

**Comment by foremtehan** [comment]
oh sorry i did a copy a paste from the doc

here's my then https://github.com/joanhey/AdapterMan/pull/65
